[package]
name = "fxllencode/roxios"
version = "1.1.9"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
promise = "evaera/promise@4.0.0"
URL = "csqrl/url@0.0.0"